<?php

declare (strict_types=1);
namespace Flames\Code\Upgrade\UpgradeInstaller;

use Flames\Code\Upgrade\ThirdParty\Composer\Installer\InstallationManager;
use Flames\Code\Upgrade\ThirdParty\Composer\IO\IOInterface;
use Flames\Code\Upgrade\ThirdParty\Composer\Package\PackageInterface;
use Flames\Code\Upgrade\ThirdParty\Composer\Repository\InstalledRepositoryInterface;
use Flames\Code\Upgrade\ThirdParty\Composer\Util\Filesystem as ComposerFilesystem;
/**
 * @see \Flames\Code\Upgrade\UpgradeInstaller\Tests\PluginInstallerTest
 */
final class PluginInstaller
{
    private readonly InstalledRepositoryInterface $localRepository;
    private readonly IOInterface $io;
    private readonly InstallationManager $installationManager;
    private readonly ComposerFilesystem $composerFilesystem;
    public const string RECTOR_EXTENSION_TYPE = 'rector-extension';
    public const string RECTOR_EXTRA_KEY = 'rector';
    private static string $generatedFileTemplate = <<<'CODE_SAMPLE'
<?php

declare(strict_types = 1);

namespace Flames\Code\Upgrade\UpgradeInstaller;

/**
 * This class is generated by rector/extension-installer.
 * @internal
 */
final class GeneratedConfig
{
    public const EXTENSIONS = %s;

    private function __construct()
    {
    }
}

CODE_SAMPLE;
    public function __construct(private readonly \Flames\Code\Upgrade\UpgradeInstaller\Filesystem $filesystem, InstalledRepositoryInterface $localRepository, IOInterface $io, InstallationManager $installationManager, ComposerFilesystem $composerFilesystem, private readonly string $configurationFile)
    {
        $this->localRepository = $localRepository;
        $this->io = $io;
        $this->installationManager = $installationManager;
        $this->composerFilesystem = $composerFilesystem;
    }
    public function install(): void
    {
        $oldGeneratedConfigFileHash = null;
        if ($this->filesystem->isFile($this->configurationFile)) {
            $oldGeneratedConfigFileHash = $this->filesystem->hashFile($this->configurationFile);
        }
        $installedPackages = [];
        $data = [];
        foreach ($this->localRepository->getPackages() as $package) {
            if ($this->shouldSkip($package)) {
                continue;
            }
            $absoluteInstallPath = $this->installationManager->getInstallPath($package);
            $data[$package->getName()] = ['install_path' => $absoluteInstallPath, 'relative_install_path' => $this->composerFilesystem->findShortestPath(dirname($this->configurationFile), $absoluteInstallPath, \true), 'extra' => $package->getExtra()[self::RECTOR_EXTRA_KEY] ?? null, 'version' => $package->getFullPrettyVersion()];
            $installedPackages[$package->getName()] = \true;
        }
        ksort($data);
        ksort($installedPackages);
        $generatedConfigFileContents = sprintf(self::$generatedFileTemplate, var_export($data, \true), \true);
        if ($this->filesystem->hashEquals((string) $oldGeneratedConfigFileHash, $generatedConfigFileContents)) {
            return;
        }
        $this->filesystem->writeFile($this->configurationFile, $generatedConfigFileContents);
        $this->io->write('<info>flamesphp/code-installer:</info> Extensions installed');
        foreach (array_keys($installedPackages) as $name) {
            $this->io->write(sprintf('> <info>%s:</info> installed', $name));
        }
    }
    private function shouldSkip(PackageInterface $package): bool
    {
        if ($package->getType() === self::RECTOR_EXTENSION_TYPE) {
            return \false;
        }
        if (isset($package->getExtra()[self::RECTOR_EXTRA_KEY])) {
            return \false;
        }
        return \true;
    }
}
